test
multiplay/qstat pull request #104
Opened 2021-07-01 15:05 UTC by austin-barrington

2021-07-02 12:25 UTC, aaronjpitty commented on .github/workflows/release.yml
> +            windows-qstat.exe
Missing a new line :D

2021-07-02 12:25 UTC, aaronjpitty approved these changes

2021-07-02 14:49 UTC, danmrichards approved these changes

2021-07-04 14:26 UTC, stevenh requested changes
I would recommend merging #105 which adds binary versioning first then rebase so the Build CI changes aren't needed.

I've also suggested some changes to the layout.

The only other change that might be good is to only run the windows release build separately thus avoiding storing the linux assets.

2021-07-04 14:26 UTC, stevenh commented on .github/workflows/release.yml
> +          name: linux-qstat
Just use path to download all assets, this should result in
```shell
bin/windows_amd64/qstat.exe
bin/linux_amd64/qstat
```

2021-07-04 14:26 UTC, stevenh commented on .github/workflows/release.yml
> +            windows-qstat.exe
```suggestion
            bin/*
            qstat.cfg
            contrib.cfg
            LICENSE.txt
```

2021-07-04 14:26 UTC, stevenh commented on .github/workflows/release.yml
> +            windows-qstat.exe
All binaries, cfg files and license

2021-07-04 14:26 UTC, stevenh commented on .github/workflows/build.yml
> +          path: qstat.exe
```suggestion
```
No need to upload the build for PRs

2021-07-04 14:26 UTC, stevenh commented on .github/workflows/release.yml
> +          name: linux64-qstat
```suggestion
          name: linux_amd64
```
Standardised naming that also supports bulk downloads

2021-07-04 14:26 UTC, stevenh commented on .github/workflows/release.yml
> +          name: windows-qstat.exe
```suggestion
          name: windows_amd64
```
Standardised naming which also supports bulk downloads

2021-07-05 15:13 UTC, austin-barrington commented
Merged #105 and tomorrow (hopefully) i'll get to making the changes you've suggested above!

2021-07-08 09:30 UTC, stevenh requested changes

2021-07-08 09:30 UTC, stevenh commented on .github/workflows/release.yaml
> +          set QSTAT_VERSION=${{ github.event.release.tag_name }} && nmake -f Makefile.noauto windows windows_debug
```suggestion
          set QSTAT_VERSION=${{ github.event.release.tag_name }} && nmake -f Makefile.noauto windows_debug
```

2021-07-08 09:30 UTC, stevenh commented on .github/workflows/release.yaml
> +          set QSTAT_VERSION=${{ github.event.release.tag_name }} && nmake -f Makefile.noauto windows windows_debug
No need to build both versions as they just overwrite each other.

2021-07-08 09:30 UTC, stevenh commented on .github/workflows/release.yaml
> +            LICENSE.txt
Missing new line

2021-07-08 09:30 UTC, stevenh commented on .github/workflows/release.yaml
> +            binaries.zip
Why zip them?

2021-07-08 09:31 UTC, stevenh requested changes

2021-07-08 09:31 UTC, stevenh commented on .github/workflows/release.yaml
> +          path: qstat.exe
```suggestion
          path: |
            qstat.exe
            qstat.pdb
```

2021-07-14 15:27 UTC, stevenh requested changes

2021-07-14 15:27 UTC, stevenh commented on .github/workflows/release.yaml
> +          nmake -f Makefile.noauto windows windows_debug
```suggestion
          nmake -f Makefile.noauto windows_debug
```

2021-07-19 07:19 UTC, austin-barrington commented on .github/workflows/release.yaml
> +            binaries.zip
It makes it easier to upload them as assets and it keeps the dir structure in the zip folder else we have to specify each bin individually. 

When adding new items to this list or other lists. It just means it's handled by the zipping process.
```
          name: windows_amd64
          path: |
            qstat.exe
            qstat.pdb
 ``` 
 
 I don't mind either way but I feel like it's cleaner.

2021-07-19 08:42 UTC, stevenh commented on .github/workflows/release.yaml
> +            binaries.zip
From a users perspective its another step though isn't it?

2021-07-19 08:46 UTC, stevenh commented on .github/workflows/release.yaml
> +            binaries.zip
Also the binaries aren't fully useable without the config files, so keep that in mind.

2021-07-19 08:47 UTC, stevenh requested changes

2021-07-19 08:47 UTC, stevenh commented on .github/workflows/release.yaml
> +    - 'v*'
This looks wrong, surely you want it on release not push otherwise you'll be creating assets all the time.

2021-07-19 09:34 UTC, stevenh approved these changes
LGTM

2021-07-19 09:54 UTC, merged